#!/usr/bin/env python3
"""Generate stdlib/nyra_rt.h from docs/abi-manifest.toml (stable symbols only)."""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "docs" / "abi-manifest.toml"
OUT = ROOT / "stdlib" / "nyra_rt.h"


def load_manifest() -> list[dict]:
    data = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    return data.get("symbol", [])


def generate(symbols: list[dict]) -> str:
    stable = [s for s in symbols if s.get("tier") == "stable"]
    lines = [
        "/* Generated by make gen-abi-header (make/py/gen-abi-header.py) — do not edit by hand. */",
        "/* Stable nyra_rt ABI — see docs/abi-policy.md and docs/abi-manifest.toml. */",
        "#ifndef NYRA_RT_H",
        "#define NYRA_RT_H",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for sym in stable:
        since = sym.get("since", "?")
        lines.append(f"/* since Nyra {since} */")
        lines.append(f"{sym['c_sig']};")
        lines.append("")
    lines.extend(
        [
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif /* NYRA_RT_H */",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    if not MANIFEST.is_file():
        print(f"error: manifest not found: {MANIFEST}", file=sys.stderr)
        return 1
    symbols = load_manifest()
    if not symbols:
        print("error: no symbols in manifest", file=sys.stderr)
        return 1
    content = generate(symbols)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT} ({len([s for s in symbols if s.get('tier') == 'stable'])} stable symbols)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
