//! Emit Rust wrapper + Nyra bindings from a [`BindSpec`](crate::scan::BindSpec).

use std::collections::HashSet;

use crate::scan::BindSpec;
use crate::types::NyraType;

#[derive(Debug, Clone)]
pub struct GeneratedBridge {
    pub wrapper_rs: String,
    pub bindings_ny: String,
    pub dep_line: String,
}

pub fn generate_bridge(crate_name: &str, version: &str, spec: &BindSpec) -> Result<GeneratedBridge, String> {
    let rust_crate = crate_name.replace('-', "_");
    let dep_line = format!("{crate_name} = \"{version}\"");

    let mut used_types: HashSet<String> = HashSet::new();
    for item in &spec.items {
        if let Some(ref owner) = item.owner {
            used_types.insert(owner.clone());
        }
        if let Some(ref owner) = item.mapped.needs_handle_type {
            used_types.insert(owner.clone());
        }
    }
    let mut wrapper = String::from("use std::ffi::{CStr, CString};\n");
    for ty in &used_types {
        wrapper.push_str(&format!("use {crate_name}::{ty};\n"));
    }
    wrapper.push('\n');
    let mut nyra = format!(
        "// Auto-generated by nyra bindgen for {crate_name} {version}\n// Do not edit by hand.\n\n"
    );
    let mut handle_types: HashSet<String> = HashSet::new();

    for item in &spec.items {
        let m = &item.mapped;
        if let Some(ref owner) = m.needs_handle_type {
            handle_types.insert(owner.clone());
        }

        let c_params: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, p.c_type))
            .collect();
        wrapper.push_str(&format!(
            "#[no_mangle]\npub extern \"C\" fn {}({}) -> {} {{\n    {}\n}}\n\n",
            m.symbol,
            c_params.join(", "),
            m.c_return,
            m.rust_body
        ));

        let ny_params: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, p.nyra_type.nyra_ann()))
            .collect();
        nyra.push_str(&format!(
            "extern fn {}({}) -> {}\n",
            m.symbol,
            ny_params.join(", "),
            m.return_type.nyra_ann()
        ));

        let friendly = if let Some(ref owner) = item.owner {
            format!("{owner}_{}", item.fn_name)
        } else {
            item.fn_name.clone()
        };
        nyra.push_str(&format!(
            "fn {friendly}({}) -> {} {{\n",
            ny_params.join(", "),
            m.return_type.nyra_ann()
        ));
        let call_args: Vec<String> = m.params.iter().map(|p| p.name.clone()).collect();
        if m.return_type == NyraType::Void {
            nyra.push_str(&format!("    {}({})\n", m.symbol, call_args.join(", ")));
        } else {
            nyra.push_str(&format!(
                "    return {}({})\n",
                m.symbol,
                call_args.join(", ")
            ));
        }
        nyra.push_str("}\n\n");
    }

    for owner in handle_types {
        let sym = format!("{rust_crate}_{owner}_free");
        wrapper.push_str(&format!(
            "#[no_mangle]\npub extern \"C\" fn {sym}(handle: *mut std::ffi::c_void) {{\n    if !handle.is_null() {{\n        unsafe {{ drop(Box::from_raw(handle as *mut {owner})); }}\n    }}\n}}\n\n"
        ));
        nyra.push_str(&format!("extern fn {sym}(handle: ptr) -> void\n"));
        nyra.push_str(&format!("fn {owner}_free(handle: ptr) -> void {{\n    {sym}(handle)\n}}\n\n"));
    }

    Ok(GeneratedBridge {
        wrapper_rs: wrapper,
        bindings_ny: nyra,
        dep_line,
    })
}
