use crate::config::BindConfig;
use crate::parse::BindSpec;
use crate::shim::{emit_shim_c, emit_shim_cxx};

#[derive(Debug, Clone)]
pub struct GeneratedCBindings {
    pub bindings_ny: String,
    pub shim_c: Option<String>,
    pub mod_lines: Vec<String>,
    pub functions: usize,
    pub shims: usize,
    pub skipped: usize,
}

pub fn generate_bindings(config: &BindConfig, spec: &BindSpec) -> Result<GeneratedCBindings, String> {
    let header_name = config
        .header
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "header.h".into());

    let mut ny = format!(
        "// Auto-generated by `nyra bind` from {header_name}\n\
         // Regenerate: nyra bind c {} \\\n\
         //   {}import with: import \"vendor/bindings/...\"\n\n",
        config.header.display(),
        if config.link_libs.is_empty() {
            String::new()
        } else {
            format!("--lib {} ", config.link_libs.join(" --lib "))
        }
    );
    if config.cxx {
        ny.push_str(
            "// C++ interop: symbols go through vendor/bindings/shim.cpp (extern \"C\").\n\n",
        );
    }

    for st in &spec.structs {
        ny.push_str(&format!("struct {} repr(C) {{\n", st.name));
        for (fname, fty) in &st.fields {
            ny.push_str(&format!("    {fname}: {}\n", fty.nyra_ann()));
        }
        ny.push_str("}\n\n");
    }

    for func in &spec.functions {
        let params: Vec<String> = func
            .params
            .iter()
            .map(|(n, t)| format!("{n}: {}", t.nyra_ann()))
            .collect();
        ny.push_str(&format!(
            "extern fn {}({}) -> {}\n",
            func.name,
            params.join(", "),
            func.return_type.nyra_ann()
        ));
    }
    ny.push('\n');

    let header_include = config.header.display().to_string();
    let shim_c = if spec.shims.is_empty() {
        None
    } else if config.cxx {
        Some(emit_shim_cxx(&header_include, &spec.shims))
    } else {
        Some(emit_shim_c(&header_include, &spec.shims))
    };

    let mut mod_lines = Vec::new();
    for lib in &config.link_libs {
        mod_lines.push(format!("link {lib}"));
    }
    if config.cxx {
        let cxxrt = if cfg!(target_os = "macos") || cfg!(target_os = "ios") {
            "c++"
        } else {
            "stdc++"
        };
        let line = format!("link {cxxrt}");
        if !mod_lines.iter().any(|l| l == &line) {
            mod_lines.push(line);
        }
    }
    if shim_c.is_some() {
        mod_lines.push(format!("link-source {}", config.shim_source_path()));
        for inc in &config.includes {
            if config.cxx {
                let s = inc.to_string_lossy();
                if s.contains(".sdk/usr/include") || s.contains("/lib/clang/") {
                    continue;
                }
            }
            let line = format!("link -L {}", inc.display());
            if !mod_lines.iter().any(|l| l == &line) {
                mod_lines.push(line);
            }
        }
        if let Some(parent) = config.header.parent() {
            let line = format!("link -L {}", parent.display());
            if !mod_lines.iter().any(|l| l == &line) {
                mod_lines.push(line);
            }
        }
    }

    Ok(GeneratedCBindings {
        bindings_ny: ny,
        shim_c,
        mod_lines,
        functions: spec.functions.len(),
        shims: spec.shims.len(),
        skipped: spec.skipped.len(),
    })
}
