//! C shim wrappers for signatures that cannot map directly to Nyra FFI.

use clang::{Entity, Type, TypeKind};

use crate::types::NyraType;

#[derive(Debug, Clone)]
pub struct CShimFn {
    pub nyra_name: String,
    pub nyra_params: Vec<(String, NyraType)>,
    pub nyra_return: NyraType,
    /// Full C function definition (without trailing semicolon).
    pub c_definition: String,
}

/// Build a simplified Nyra-facing wrapper when direct mapping fails.
pub fn try_shim_function(entity: &Entity, name: &str) -> Option<CShimFn> {
    if entity.is_variadic() {
        return None;
    }
    let ret_ty = entity.get_result_type()?;
    let ny_ret = map_shim_type(&ret_ty, false);

    let mut ny_params = Vec::new();
    let mut c_param_decls = Vec::new();
    let mut call_args = Vec::new();

    if let Some(args) = entity.get_arguments() {
        for (i, arg) in args.into_iter().enumerate() {
            let arg_ty = arg.get_type()?;
            let _c_ty = arg_ty.get_display_name();
            let ny_ty = map_shim_type(&arg_ty, true);
            let pname = arg
                .get_name()
                .filter(|n| !n.is_empty())
                .unwrap_or_else(|| format!("arg{i}"));
            let pname = crate::names::sanitize_identifier(&pname);
            ny_params.push((pname.clone(), ny_ty));
            c_param_decls.push(format!("{} {}", shim_c_type(&arg_ty), pname));
            call_args.push(cast_to_c(&arg_ty, &pname));
        }
    }

    let c_ret = shim_c_return_type(&ret_ty);
    let shim_name = format!("nyra_shim_{name}");
    let params_joined = c_param_decls.join(", ");
    let call_joined = call_args.join(", ");
    let c_body = if ny_ret == NyraType::Void {
        format!(
            "{c_ret} {shim_name}({params_joined}) {{\n    {name}({call_joined});\n}}"
        )
    } else {
        format!(
            "{c_ret} {shim_name}({params_joined}) {{\n    return {name}({call_joined});\n}}"
        )
    };

    Some(CShimFn {
        nyra_name: shim_name,
        nyra_params: ny_params,
        nyra_return: ny_ret,
        c_definition: c_body,
    })
}

pub fn emit_shim_c(header_include: &str, shims: &[CShimFn]) -> String {
    let mut out = String::from(
        "/* Auto-generated by `nyra bind c` — do not edit. */\n\
         #include <stdint.h>\n",
    );
    out.push_str(&format!("#include \"{header_include}\"\n\n"));
    for shim in shims {
        out.push_str(&shim.c_definition);
        out.push_str("\n\n");
    }
    out
}

fn map_shim_type(ty: &Type, is_param: bool) -> NyraType {
    match ty.get_kind() {
        TypeKind::Void => NyraType::Void,
        TypeKind::Bool => NyraType::Bool,
        TypeKind::CharS | TypeKind::SChar | TypeKind::CharU | TypeKind::UChar
        | TypeKind::Short | TypeKind::Int => NyraType::Int("i32"),
        TypeKind::UShort | TypeKind::UInt => NyraType::Int("u32"),
        TypeKind::Long | TypeKind::LongLong => NyraType::Int("i64"),
        TypeKind::ULong | TypeKind::ULongLong => NyraType::Int("u64"),
        TypeKind::Float | TypeKind::Double | TypeKind::LongDouble => NyraType::F64,
        TypeKind::Pointer => {
            let pointee = ty.get_pointee_type();
            if let Some(pt) = pointee {
                let pk = pt.get_kind();
                if pk == TypeKind::CharS || pk == TypeKind::SChar || pk == TypeKind::CharU {
                    return NyraType::String;
                }
            }
            NyraType::Ptr
        }
        TypeKind::ConstantArray | TypeKind::IncompleteArray if is_param => NyraType::Ptr,
        TypeKind::Typedef | TypeKind::Elaborated => {
            map_shim_type(&ty.get_canonical_type(), is_param)
        }
        _ => NyraType::Ptr,
    }
}

fn shim_c_type(ty: &Type) -> &'static str {
    match ty.get_kind() {
        TypeKind::Bool => "int",
        TypeKind::CharS | TypeKind::SChar | TypeKind::CharU | TypeKind::UChar
        | TypeKind::Short | TypeKind::Int => "int32_t",
        TypeKind::UShort | TypeKind::UInt => "uint32_t",
        TypeKind::Long | TypeKind::LongLong => "int64_t",
        TypeKind::ULong | TypeKind::ULongLong => "uint64_t",
        TypeKind::Float | TypeKind::Double | TypeKind::LongDouble => "double",
        TypeKind::Pointer => {
            let pointee = ty.get_pointee_type();
            if let Some(pt) = pointee {
                let pk = pt.get_kind();
                if pk == TypeKind::CharS || pk == TypeKind::SChar || pk == TypeKind::CharU {
                    return "const char *";
                }
            }
            "void *"
        }
        TypeKind::Typedef | TypeKind::Elaborated => shim_c_type(&ty.get_canonical_type()),
        _ => "void *",
    }
}

fn shim_c_return_type(ty: &Type) -> String {
    match ty.get_kind() {
        TypeKind::Void => "void".into(),
        TypeKind::Bool => "int".into(),
        TypeKind::CharS | TypeKind::SChar | TypeKind::CharU | TypeKind::UChar
        | TypeKind::Short | TypeKind::Int => "int32_t".into(),
        TypeKind::UShort | TypeKind::UInt => "uint32_t".into(),
        TypeKind::Long | TypeKind::LongLong => "int64_t".into(),
        TypeKind::ULong | TypeKind::ULongLong => "uint64_t".into(),
        TypeKind::Float | TypeKind::Double | TypeKind::LongDouble => "double".into(),
        TypeKind::Pointer => {
            let pointee = ty.get_pointee_type();
            if let Some(pt) = pointee {
                let pk = pt.get_kind();
                if pk == TypeKind::CharS || pk == TypeKind::SChar || pk == TypeKind::CharU {
                    return "const char *".into();
                }
            }
            "void *".into()
        }
        TypeKind::Typedef | TypeKind::Elaborated => shim_c_return_type(&ty.get_canonical_type()),
        _ => "void *".into(),
    }
}

fn cast_to_c(ty: &Type, var: &str) -> String {
    let c_ty = ty.get_display_name();
    match ty.get_kind() {
        TypeKind::Bool
        | TypeKind::CharS
        | TypeKind::SChar
        | TypeKind::CharU
        | TypeKind::UChar
        | TypeKind::Short
        | TypeKind::Int
        | TypeKind::UShort
        | TypeKind::UInt
        | TypeKind::Long
        | TypeKind::LongLong
        | TypeKind::ULong
        | TypeKind::ULongLong
        | TypeKind::Float
        | TypeKind::Double
        | TypeKind::LongDouble => var.to_string(),
        TypeKind::Pointer => {
            let pointee = ty.get_pointee_type();
            if let Some(pt) = pointee {
                let pk = pt.get_kind();
                if pk == TypeKind::CharS || pk == TypeKind::SChar || pk == TypeKind::CharU {
                    return var.to_string();
                }
            }
            format!("({c_ty}){var}")
        }
        TypeKind::Typedef | TypeKind::Elaborated => cast_to_c(&ty.get_canonical_type(), var),
        _ => format!("({c_ty}){var}"),
    }
}
